PROJECTS = {
    "everheal": {
        "slug": "everheal",
        "title": "EverHeal",
        "icon": "🏥",
        "icon_class": "project-icon--health",
        "role": "Frontend Developer & Team Leader",
        "date": "Dec 2025 — Present",
        "summary": "Healthcare consultation platform with improved UI/UX for patient-doctor interactions. Led the development team and represented EverHeal at the EDC College-Level Competition, advancing to Round 2.",
        "tech": ["HTML", "CSS", "JavaScript"],
        "github_url": "https://github.com/Dhruv-Mishra-905/EverHeal",
        "live_url": "https://everheal.netlify.app/",
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "EverHeal",
        "readme_path": "",
        "ref": "main",
        "featured": True,
    },
    "crypto-tracker": {
        "slug": "crypto-tracker",
        "title": "Crypto Tracker",
        "icon": "📈",
        "icon_class": "project-icon--crypto",
        "role": "Full Stack Developer",
        "date": "Nov 2025 — Dec 2025",
        "summary": "React web application integrating REST APIs for real-time cryptocurrency prices, trends, and market data with an enhanced Bootstrap interface.",
        "tech": ["React", "Bootstrap", "REST API"],
        "github_url": "https://github.com/Dhruv-Mishra-905/react-project-hub/tree/main/cryptoTracker",
        "live_url": "https://simplecryptotracker.netlify.app/",
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "react-project-hub",
        "readme_path": "cryptoTracker",
        "ref": "main",
        "featured": True,
    },
    "color-detection": {
        "slug": "color-detection",
        "title": "Color Detection",
        "icon": "🎨",
        "icon_class": "project-icon--color",
        "role": "Python Developer",
        "date": "Sep 2025 — Oct 2025",
        "summary": "Python application using OpenCV to detect and classify colors through pixel and color-range analysis with core computer vision techniques.",
        "tech": ["Python", "OpenCV"],
        "github_url": "https://github.com/Dhruv-Mishra-905/Python-Projects/tree/main/Learning/color-Detection",
        "live_url": None,
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "Python-Projects",
        "readme_path": "Learning/color-Detection",
        "ref": "main",
        "featured": True,
    },
    "face-recognition": {
        "slug": "face-recognition",
        "title": "Face Recognition System",
        "icon": "👤",
        "icon_class": "project-icon--face",
        "role": "Frontend & Backend Contributor",
        "date": "Aug 2025 — Sep 2025",
        "summary": "Automated attendance system integrating frontend features with backend Python scripts for an OpenCV-based face recognition workflow. Advanced to Round 2 of Smart India Hackathon (SIH) 2025.",
        "tech": ["Python", "OpenCV", "HTML", "CSS"],
        "github_url": "https://github.com/Dhruv-Mishra-905/Python-Projects/tree/main/Learning/Face-Recognise",
        "live_url": None,
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "Python-Projects",
        "readme_path": "Learning/Face-Recognise",
        "ref": "main",
        "featured": True,
    },
    "svms": {
        "slug": "svms",
        "title": "Society Visitor Management System",
        "icon": "🏢",
        "icon_class": "project-icon--svms",
        "role": "Software Development Intern",
        "date": "Jun 2026 — Jul 2026",
        "summary": "Full-stack visitor management system for Central Coalfields Limited with form handling, dashboards, and streamlined check-in workflows.",
        "tech": ["React", "Node.js", "MySQL"],
        "github_url": "https://github.com/Dhruv-Mishra-905/Main-Projects/tree/main/SVMS/society-visitor-management-system",
        "live_url": "https://society-visitor-management-system.onrender.com/",
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "Main-Projects",
        "readme_path": "SVMS/society-visitor-management-system",
        "ref": "main",
        "featured": False,
    },
    "snac": {
        "slug": "snac",
        "title": "Smart Network Analytics Center",
        "icon": "📡",
        "icon_class": "project-icon--snac",
        "role": "Software Development Intern",
        "date": "May 2026 — Jun 2026",
        "summary": "Dashboard components for real-time network analytics and data visualization at Usha Martin's SNAC facility.",
        "tech": ["JavaScript", "Data Viz", "Analytics"],
        "github_url": "https://github.com/Dhruv-Mishra-905/Main-Projects/tree/641abd0128d91461cc36044abcb8a4cb42b2fdb0/Smart%20Network%20Analytics%20Center%20(SNAC)/Smart%20Network%20Analytics%20Center%20(SNAC)",
        "live_url": None,
        "github_owner": "Dhruv-Mishra-905",
        "github_repo": "Main-Projects",
        "readme_path": "Smart Network Analytics Center (SNAC)/Smart Network Analytics Center (SNAC)",
        "ref": "641abd0128d91461cc36044abcb8a4cb42b2fdb0",
        "featured": False,
    },
}


def get_project(slug):
    return PROJECTS.get(slug)


def get_all_projects():
    return list(PROJECTS.values())


def get_featured_projects():
    return [p for p in PROJECTS.values() if p.get("featured")]
