services:
  - type: web
    name: dhruv-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORTFOLIO_SECRET_KEY
        generateValue: true
